# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5Q-CL0xQ9B4K2BSfwlmjXoKcQvWtwHR
"""

!pip install experta

!pip install --upgrade frozendict

def backward_chaining(goal, facts, rules):
  if goal in facts:
    return True
  for rule in rules:
    if rule["then"] == goal:
      if all(backward_chaining(cond, facts, rules) for cond in rule["if"]):
        return True
  return False

facts = {"like_computers", "solves_problems", "likes_to_design"}
rules = [
    {"if": {"like_computers", "solves_problems"}, "then": "should_be_engineer"},
    {"if": {"should_be_engineer", "likes_programing"}, "then": "software_engineer"},
    {"if": {"should_be_engineer", "likes_to_design"}, "then": "ui/ux_engineer"}
]

goal = "ui/ux_engineer"
result = backward_chaining(goal, facts, rules)
print(f"is '{goal} probable? ->", result)