# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5Q-CL0xQ9B4K2BSfwlmjXoKcQvWtwHR
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *
class SistemPakarMedis(KnowledgeEngine):
  @Rule(Fact(demam=True) & Fact(batuk=True))
  def flu(self):
    print("Diagnosis : flu.")

  @Rule(Fact(sakit_tenggorokan=True) & Fact(demam=True))
  def throat_infection(self):
    print("Diagnosis : radang tenggorokan.")

  @Rule(Fact(nyeri_otot=True) & Fact(nyeri_perut=True))
  def hernia(self):
    print("Diagnosis : hernia.")


engine = SistemPakarMedis()
engine.reset()
engine.declare(Fact(demam=True))
engine.declare(Fact(batuk=True))
engine.run()