# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvJF9r5L561S8OWWaUmLzyjS5JfiijW-
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class diagnosis(KnowledgeEngine):
  @Rule(Fact(demam=True) & Fact(lelah=True) & Fact(leher_bengkak=True) & Fact(mulut_kering=True))
  def gondongan(self):
    print("Diagnosis: Anda mungkin terkena Gondongan.")

  @Rule(Fact(sakit_perut=True) & Fact(diare=True) & Fact(kram=True) & Fact(mual=True))
  def ibs(self):
    print("Diagnosis: Anda mungkin mengalami Irritable Bowel Syndrome (IBS).")

  @Rule(Fact(mual=True) & Fact(kembung=True) & Fact(sendawa=True) & Fact(sakit_tenggorokan=True))
  def gerd(self):
    print("Diagnosis: Anda mungkin mengalami GERD (Gastroesophageal Reflux Disease).")

  @Rule(Fact(demam=False) & Fact(lelah=False) & Fact(leher_bengkak=False) & Fact(mulut_kering=False) &
        Fact(sakit_perut=False) & Fact(diare=False) & Fact(kram=False) & Fact(mual=False) &
        Fact(kembung=False) & Fact(sendawa=False) & Fact(sakit_tenggorokan=False))
  def sehat(self):
    print("Diagnosis: Anda tampaknya sehat.")

def get_input():
  def ask_question(question):
    return input(question + " (yes/no): ").strip().lower() == "yes"

  return {
      "demam": ask_question("Apakah Anda mengalami demam?"),
      "lelah": ask_question("Apakah Anda merasa lelah?"),
      "leher_bengkak": ask_question("Apakah leher Anda bengkak?"),
      "mulut_kering": ask_question("Apakah mulut Anda terasa kering?"),
      "sakit_perut": ask_question("Apakah Anda merasakan sakit perut?"),
      "diare": ask_question("Apakah Anda mengalami diare?"),
      "kram": ask_question("Apakah Anda mengalami kram perut?"),
      "mual": ask_question("Apakah Anda merasa mual?"),
      "kembung": ask_question("Apakah Anda merasa kembung?"),
      "sendawa": ask_question("Apakah Anda sering bersendawa?"),
      "sakit_tenggorokan": ask_question("Apakah Anda mengalami sakit tenggorokan?")
  }

if __name__ == "__main__":
  symptoms = get_input()
  engine = diagnosis()
  engine.reset()

  for symptom, present in symptoms.items():
    engine.declare(Fact(**{symptom: present}))

  engine.run()

"""% Fakta: Anak-anak Ayah
anak_ayah(lina).
anak_ayah(miko).
anak_ayah(nita).
anak_ayah(oki).
anak_ayah(pina).

% Riko bukan anak Ayah
bukan_anak_ayah(riko).

% Yang suka buku
suka_buku(lina).
suka_buku(nita).

% Aturan pemberian hadiah
mendapat_hadiah(Anak, buku) :-
    anak_ayah(Anak),
    suka_buku(Anak).

mendapat_hadiah(Anak, mainan) :-
    anak_ayah(Anak),
    \+ suka_buku(Anak).

% Pertanyaan sebagai predikat untuk jawaban

% a. Siapa saja anak Ayah?
jawaban_a(Anak) :-
    anak_ayah(Anak).

% b. Siapa saja yang mendapatkan buku dari Ayah?
jawaban_b(Anak) :-
    mendapat_hadiah(Anak, buku).

% c. Siapa saja yang mendapatkan mainan dari Ayah?
jawaban_c(Anak) :-
    mendapat_hadiah(Anak, mainan).

% d. Apakah Pina mendapatkan buku dari Ayah?
jawaban_d :-
    mendapat_hadiah(pina, buku).

% e. Apakah Riko tidak mendapatkan apa-apa dari Ayah?
jawaban_e :-
    bukan_anak_ayah(riko),
    \+ mendapat_hadiah(riko, _).

"""



"""?- jawaban_a(X).    % untuk soal a
?- jawaban_b(X).    % untuk soal b
?- jawaban_c(X).    % untuk soal c
?- jawaban_d.       % untuk soal d
?- jawaban_e.       % untuk soal e

"""